name: CI

on:
  push:
  pull_request:

jobs:
  build:
    uses: 2bbb/of-actions/.github/workflows/build-addon.yml@main
    with:
      of_version: "0.12.1"
      addon_name: "ofxSkia"
      test_app: "testApp"
      test_mode: "test"
      pre_build_script: "scripts/ci_build_skia.sh"
      pre_build_script_windows: "scripts/ci_build_skia_windows.ps1"
      pre_build_cache_path: "libs/skia"
      pre_build_cache_key: "skia-chrome-m130-v3"
